### ISSUE TITLE
Cannot read 'peerId'

### ISSUE THREAD

**Issue by no-do-not-track-me** [spknetwork/video-encoder#20]
```
3|video  | 2022-07-09T10:32:57: TypeError: Cannot read properties of undefined (reading 'peerId')
3|video  | 2022-07-09T10:32:57:     at EncoderService.createJob (/Users/sagar/projects/3speak/video-encoder/dist/modules/core/encoder.service.js:379:49)
3|video  | 2022-07-09T10:32:57:     at GatewayClient.queueJob (/Users/sagar/projects/3speak/video-encoder/dist/modules/core/gatewayClient.service.js:34:49)
3|video  | 2022-07-09T10:32:57:     at runMicrotasks (<anonymous>)
3|video  | 2022-07-09T10:32:57:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
3|video  | 2022-07-09T10:33:56: https://encoder-gateway.infra.3speak.tv
```

**Comment by Rishi556** [comment]
Looks like related to https://github.com/spknetwork/video-encoder/issues/18. You running the latest version, since it was supposed to be fixed with https://github.com/spknetwork/video-encoder/commit/521a3699f22c6e04543a7258b93c11fd58dbb054. If not, you can set env variable `ENABLE_P2P` to true.

**Comment by vaultec81** [comment]
@no-do-not-track-me Is this still a problem with the update? If so, please provide:
- NodeID (found in config file, if available)
- Github commit hash

I will close after 24 hours of inactively. Reopen if it is still an issue
